- src/lib/vm/gc.rs
- src/lib/vm/objects.rs
- src/lib/vm/vm.rs
- src/main.rs
Previously we didn't drop memory in many cases. Running `valgrind` on hello world shows this clearly:
```
==3110== HEAP SUMMARY:
==3110==     in use at exit: 8,389 bytes in 44 blocks
==3110==   total heap usage: 27,864 allocs, 27,820 frees, 17,935,698 bytes allocated
==3110==
==3110== LEAK SUMMARY:
==3110==    definitely lost: 0 bytes in 0 blocks
==3110==    indirectly lost: 0 bytes in 0 blocks
==3110==      possibly lost: 0 bytes in 0 blocks
==3110==    still reachable: 8,389 bytes in 44 blocks
==3110==         suppressed: 0 bytes in 0 blocks
```
This PR fixes that.
First, some of those leaks are because we called `process::exit` without giving parent frames the chance to `drop` items. This is fixed in https://github.com/softdevteam/yksom/commit/1cc668dbf3e719d4167c0329cb293101453c20db. …
> Drop memory properly

- src/lib/vm/objects.rs
- src/lib/vm/vm.rs
There is an element of "2 for 1" in this PR. https://github.com/softdevteam/yksom/commit/23a03e051d3cdfc2505cc5fff7ae8f46d0642dd6 fixes an infinite recursion problem in boxing integers. While doing that, I noticed that we had become highly inconsistent in the return types we used, particularly in integer creating/boxing/unboxing.  https://github.com/softdevteam/yksom/commit/833ddb8fc562c06b15dfb6dca0c812c3f6420e60 fixes that problem.
> Fix boxing of ints

- src/lib/vm/gc.rs
- src/lib/vm/objects.rs
- src/lib/vm/vm.rs
Without this we can't write VM functions that return `&self` as a `Val`, because `&self` will be a reference to a concrete struct, and we can't turn that into a Val, because `Val::from_obj` takes a `T`, not an `&T`. At its simplest, this means we couldn't write the following identity function:
```
struct S;
impl Obj for S {}
impl S {
fn identity(&self) -> Val {
// what goes here?
}
}
```
This commit adds a way to turn a `&T` back into a ThinObj/GcBox/Gc. It allows us to express the identity function as follows:
```
impl S {
fn identity(&self) -> Val {
Val::restore(self)
}
}
```
This is clearly dangerous, because it assumes that the memory pointed to by `&self` is part of a ThinObj/GcBox combo. If that isn't true, all sorts of bad things will happen. Fortunately it's relatively easy to …
> Allow object references to be converted back into ThinCells/Gcs.

- lib/SOM/String.som
- src/lib/compiler/ast.rs
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/instrs.rs
- src/lib/compiler/som.y
- src/lib/vm/objects.rs
- src/lib/vm/vm.rs
This PR handles SOM keyword messages somewhat properly (i.e. functions which take named arguments, which is a Smalltalk staple). This is enough for us to implement the concatenate message on strings, at least.  The following program:
```
run = (('Hello, World from' concatenate: ' SOM') println )
```
prints "Hello, World from SOM". The main commit is https://github.com/softdevteam/yksom/pull/6/commits/5099036889bbd438484c3fe49ef9ad0450506adc; the other commits are mostly tidying up minor issues and should be fairly easy to assess.
> Handle keyword arguments

- src/lib/vm/objects.rs
- src/lib/vm/vm.rs
`gc_obj` returns `Gc<ThinObj>`: the `ThinObj` part of that has turned out to be much more important than the `Gc` part. So this PR renames the `gc_obj` function to `toobj` (https://github.com/softdevteam/yksom/commit/f41046c30d53a7bc4f0bd6db82c90124000eeaf9) and fixes up some associated variables (https://github.com/softdevteam/yksom/commit/16789cb300e9bf9edc025c5685b1e98095930d0c). This is a mostly mechanical change.
> Rename gcobj to obj

- src/lib/vm/gc.rs
- src/lib/vm/objects.rs
This adds a simple `Gc::new` function which creates a new GC'd object of an arbitrary type (previously we only offered the indirect `GcBox::alloc` approach. This is likely to be useful in several places.
> Add Gc::new.

- src/lib/vm/gc.rs
- src/lib/vm/objects.rs
This fixes and expands a few critical doc strings (as promised on #9).
> Better docs

- src/lib/vm/objects.rs
The main aim of this PR is to make casting from an `Obj` to a concrete struct faster (https://github.com/softdevteam/yksom/commit/654e044bbec3df77650e3f4fe334fa63c491e528). As a secondary aim, this also makes the boilerplate surrounding `Obj`s slightly less offensive (https://github.com/softdevteam/yksom/commit/ace48f549fe4033e13aad315aea16c3de69ff373), and then removes uses of the `Any` type entirely (https://github.com/softdevteam/yksom/commit/256c19c18861bc3545921798b09c2b89a2f84890). The individual commit messages -- particularly for the first commit -- hopefully explain things in sufficient detail.
> Faster casting

- src/lib/vm/objects.rs
- src/lib/vm/vm.rs
The big problem with our previous `Val` scheme is that you had to call `Val::tobj()` in order to get something you could then turn into a `&T` normal Rust reference. Because `tobj` returns a temporary value (since it might have to box an unboxed value), this meant that you couldn't store references to a `Val`'s underlying object without jumping through hoops.
This PR fixes that, in two main stages. First, we introduce our own type ID scheme (https://github.com/softdevteam/yksom/commit/d42c95d51140a3a1d7d0eda52830e1cd7f12a896) instead of using `TypeId` (which uses the `'static` lifetime, which causes us various problems). Then we introduce a new function `Val::gcbox_cast` (https://github.com/softdevteam/yksom/commit/143e4f6b4020e1583b9030aafec2c682d879adfb) which allows one to cast a `Val` …
> Get normal Rust references to objects when needed

- src/lib/compiler/ast.rs
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/cobjects.rs
- src/lib/compiler/instrs.rs
- src/lib/compiler/som.y
- src/lib/vm/objects.rs
- src/lib/vm/vm.rs
Needs #12 to be merged first.
This PR adds local variables to SOM methods: assigning and reading from variables. The first commit first sorts some mess out in the grammar (mea culpa): the second commit is the meat of things.
This allows us to run programs such as the following:
```
Hello = (
run = (
| t1 t2 |
t1 := 'Hello '.
t2 := t1 concatenate: 'world'.
t2 println.
)
)
```
which prints out ... wait for it ... "Hello world".
> Add local variables and assignments

- Cargo.toml
- lang_tests/hello_world1.som
- lang_tests/hello_world2.som
- lang_tests/run.rs
- lang_tests/unassigned_var.som
- lang_tests/unknown_var.som
- src/main.rs
This PR adds a simple testing framework for language level tests. It makes most sense to check it out locally and see what it does, but, in essence:
```
Finished dev [unoptimized + debuginfo] target(s) in 28.29s
Running target/debug/deps/yksom-a28e908f2324d21c
running 8 tests
test vm::gc::tests::test_gc_new ... ok
test vm::objects::tests::test_gcbox_cast ... ok
test vm::objects::tests::test_cast ... ok
test vm::objects::tests::test_boxed_int ... ok
test vm::objects::tests::test_isize ... ok
test vm::objects::tests::test_recovery ... ok
test vm::objects::tests::test_usize ... ok
test vm::vm::tests::test_frame ... ok
test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
Running target/debug/deps/yksom-13f099066134e3d5
running 0 tests
test result: ok. 0 passed; 0 failed; …
```
> Test framework

- Cargo.toml
- lang_tests/hello_world1.som
- lang_tests/hello_world2.som
- lang_tests/run.rs
- lang_tests/unassigned_var.som
- lang_tests/unknown_var.som
This ports yksom to use `lang_tester`. Mostly -- happily! -- this involves deleting code.
> Port to lang_tester.

- src/lib/vm/gc.rs
This managed to slip through unnoticed.
> Fix comment: `blank_alloc` to `alloc_blank`

- Cargo.toml
- build.rs
Using `rerun_except` helps avoid unnecessary rebuilds just because we've changed a language test.
> Recompile less often.

- build.rs
- src/lib/compiler/ast_to_instrs.rs
- src/lib/vm/objects.rs
Fixing these (thanks to `cargo fix`) removes a large number of warnings.
> Not using "dyn" for trait objects is now deprecated.

- Cargo.toml
- src/lib/vm/objects.rs
enum-primitive-derive isn't maintained and doesn't have a very nice way of converting a number into an enum. num_enum is a little better in that regard and is actively maintained, so we might even be able to drop the try_into at some point.
> Move from enum-primitive-derive to num_enum.

- Cargo.toml
- src/lib/vm/objects.rs
- src/lib/vm/vm.rs
The top-level `downcast` function isn't hugely elegant, but it is simple: we might be able to find a nicer way of doing this in future.
> Port to the natrob library.

- src/lib/vm/mod.rs
- src/lib/vm/objects.rs
- src/lib/vm/val.rs
- src/lib/vm/vm.rs
This is a non-functional change, but it hopefully makes the code easier to read: it moves the `Val` struct (and some associated bits) into its own module. `objects.rs` then becomes more clearly "SOM objects" and `val.rs` "cunning optimisations to squeeze everything into a machine word". I've done this over several commits to make it easier to review.
> Break out the Val struct (and friends)

- src/lib/vm/val.rs
This comment is also present (as it should be) in objects.rs, which makes a great deal more sense.
> Remove duplicate comment.

- Cargo.toml
- src/lib/vm/mod.rs
- src/lib/vm/objects.rs
- src/lib/vm/val.rs
- src/lib/vm/vm.rs
- src/main.rs
The problem we had before is that `VMError` is, naturally, a fairly large enum: on a 64 bit machine it is currently 32 bytes. Before this commit, we have lots of functions with a return type of `Result<Val, VMError>` -- which is 40 bytes big! This is going to cause things to continually spill to the stack, which is not good for performance.
This commit does two things (in one go, because it made more sense that way): it changes `Result<Val, VMError>` into `Result<Val, Box<VMError>>` and then makes a new type `ValResult` which is a custom representation of that type. `ValResult` is a machine word big, so in essence this commit turns the 40 bytes of `Result<Val, VMError>` into the 8 bytes of `ValResult`.
The underlying technique is pretty simple: we have spare tag bits in `Val`, so we can …
> Use a custom, compact representation of Result<Val, Box<VMError>>.

- .gitignore
It's not useful for these to show up in "git status", or for their presence to trigger a rebuild through rerun_except.
> Ignore core dumps.

- lang_tests/int1.som
- lang_tests/int2.som
- lang_tests/int3.som
- lang_tests/int4.som
- lang_tests/int5.som
- lib/SOM/Integer.som
- src/lib/compiler/ast.rs
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/cobjects.rs
- src/lib/compiler/instrs.rs
- src/lib/compiler/som.y
- src/lib/vm/objects.rs
- src/lib/vm/vm.rs
Including support for +, -, *, and /. Note that SOM (like most Smalltalks) parses expressions such as "2 + 3 * 4" as "(2 + 3) * 4": it has no concept of operator precedence, treating all binary operations as left associative.
> Add basic integer support.

- .travis.yml
Shamelessly copied from grmtools. I don't think I can test this before it's merged, but I might be very wrong. Any thoughts?
> Generate cargo doc information on gh-pages for each PR.

- .travis.yml
Instead of being `yksom/yksom`, this will make it appear as `yksom/api` (leaving us wiggle room if we want to put non-API docs on gh-pages later).
> Change the name on gh-pages of the internal API documentation.

- .buildbot.sh
The version of git on our buildbot machine doesn't have `git branch --show-current`, leading to our buildbot script failing (but, annoyingly, in a way that doesn't lead to an error).
> Fix our buildbot config for old versions of git.

- src/lib/vm/val.rs
This is one of those "what was I thinking?!" moments where it's hard to imagine how I got so confused that I made the mistake this commit fixes.
yksom, correctly, stops you trying to downcast a `Val` to an `Int`. However, the `*downcast` functions took that too far by also trying to stop you checking whether a run-time `Val` that happened to be an `Int` could be downcast or not. If you did, you got (in debug mode) an assertion failure or (in runtime mode) undefined behaviour. This simple commit rectifies this mistake by explicitly checking for tagged integers when downcasting.
> Downcasting on tagged integers needs to be handled.

- .buildbot.sh
yksom's debug and release mode are somewhat different, so it's worth taking the (smallish) extra time to test both.
> Have buildbot test release mode too.

- src/lib/vm/core.rs
- src/lib/vm/mod.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/double.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/objects/string_.rs
- src/lib/vm/val.rs
- src/main.rs
This was introduced because I thought we would need a ternary return type to deal with SOM's closure returns. However, the recent reorganisation of the core interpreter loop has removed that need (the ternary aspect now being confined purely to the few functions related to message sends). We now only need a binary return type which means we're better off simply using the normal `Result` type (which has the pleasant bonus of allowing us to use the `?` operator).
This commit thus removes the custom `ValResult` type and replaces it with `Result<Val, Box<VMError>>`. Most of this commit was performed by `srep`, with a small number of fix-ups by hand.
There appears to be a tiny performance benefit from this PR, but it's small enough that it's not really worth worrying about (my guess is that in …
> Remove ValResult

- lang_tests/double10.som
- lang_tests/obj1.som
- lang_tests/obj2.som
- lib/SOM/Double.som
- lib/SOM/False.som
- lib/SOM/Object.som
- lib/SOM/True.som
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/double.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/val.rs
This PR adds more comparisons to yksom: reference equality (https://github.com/softdevteam/yksom/commit/1dca2bc9024d03becd7d92a4c7abf1a372765c03) and various comparisons for doubles (https://github.com/softdevteam/yksom/commit/82d35c5238038d79c7e99498d0988e4359a06dca). Notice that the former commit means that we diverge slightly from SOM's current semantics (see https://github.com/SOM-st/SOM/issues/23) although I think it's fair to say that @smarr thinks the approach we're taking in this PR is the right one (and if I've got that wrong, hopefully he'll shout!).
> More comparisons

- Cargo.toml
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/cobjects.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/method.rs
This PR is mostly about precalculating the maximum stack size a block can possibly use at run-time so that we can remove some dynamic checks. This allows to use a fixed-size SOM stack, which means that we can avoid checking whether resizing (etc.) is necessary
(i.e. we can push elements onto the stack without any branching). This gives us roughly a 2.5% gain on our little while benchmark.
The main bulk of this PR is in https://github.com/softdevteam/yksom/commit/7d4ab33a6b5da7012d88788c9d9224398392f14c; the other commits are relatively minor.
> Statically calculate stack sizes

- lang_tests/unassigned_var.som
- src/lib/vm/core.rs
Previously we threw an error in such cases. While, arguably, that might be better language design, it doesn't match SOM's semantics. So this commit fixes that.
The implementation is not particularly efficient in a reference counted GC (we increment nil's reference count only to decrement it on the first assignment to a var), but it's probably not worth optimising this at this stage.
> Reading from an unassigned SOM variable should return 'nil'.

- Cargo.toml
- lang_tests/double12.som
- lang_tests/int26.som
- lang_tests/int27.som
- lang_tests/int28.som
- lang_tests/int29.som
- lib/SOM/Double.som
- lib/SOM/Integer.som
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/double.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/val.rs
This adds the sqrt primitive to yksom for Int, BigInt and Double.
> Add sqrt primitive.

- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/cobjects.rs
- src/lib/compiler/instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/class.rs
This PR slightly simplifies yksom's bytecode (well, not that it's "byte"code, but you get the idea) by getting rid of the idea of a constant pool of integers and strings. This seemed like a good idea when I didn't understand SOM, but it's now clearly overkill: the idea of pooled integers, in particular, makes very little sense in the presence of tagged integers. Once integers are removed, then the only thing left is strings, at which point we don't have a constant pool but a string pool. The two commits make these two changes in order.
> Simplify bytecode

- lib/SOM/String.som
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/val.rs
This PR adds simple support for inline caches during method lookup. The main commit is https://github.com/softdevteam/yksom/commit/0950f3de11a4f8dd75476e166df84a1a1e46cece and it's probably worth starting with that commit's message and then going backwards to the two preceding commits (which are really just warm-ups for that main commit). This is an important optimisation: on our simple while loop, it improves performance by over 20%.
> Add an inline cache

- src/lib/compiler/ast_to_instrs.rs
- src/lib/mod.rs
- src/lib/vm/core.rs
Note that Clippy has a pronounced dislike of comparing floats: in our case, such comparisons are entirely sensible. Turning this warning off is the only way to maintain our sanity.
> Various suggestions from Clippy.

- src/lib/vm/objects/integers.rs
Sqrt should return an Int if the sqrt of a BigInt can be represented as an isize.
> Sqrt should return an Int where possible.

- src/lib/vm/core.rs
- src/lib/vm/objects/double.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/val.rs
After renaming `bit_xor` to `xor`, this PR simply sorts out the order that functions are written in so that we're more consistent across structs -- this PR has no functional change. @ummarikar This one is for you to review.
bors delegate=ummarikar
> Reorder functions in structs

- Cargo.toml
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/block.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/mod.rs
Previously, in order to execute a method you had to carry around its class, since the method's program counter was relative to the class -- in other words one would use a `(Class, Method)` pair to execute a method. The original idea for this was because this makes it easier to unload classes -- which SOM never does. So it's extra complexity, and an extra performance overhead, for no gain.
This PR thus simplifies the VM so that methods can be executed without needing a pointer to the class. This has a number of knock-on effects because various things that modules need (e.g. sends, strings) were also stored on classes. Most of the commits in this PR thus move one thing at a time from classes to the main VM. In a sense, the easy bit is in the final commit (b9a3aa61), and it might be easiest …
> Make method execution only require method pointers.

- src/lib/compiler/ast_to_instrs.rs
- src/lib/vm/val.rs
Previously we used (sort of) null `GCBOX`'s as an illegal value. The problem with this is that we were haphazard in checking whether such values were ever used for anything *and* we only did so in debug mode. Any mistakes in their use were likely to end badly. This commit tentatively adds illegal values as an explicitly tagged entity: that means that we can't use them incorrectly, even in release mode. This probably slightly slows things down, but not enough that I can measure.
> Make illegal values an explicitly tagged value.

- src/lib/mod.rs
- src/lib/vm/core.rs
- src/lib/vm/mod.rs
- src/lib/vm/somstack.rs
This moves from using ArrayVec to a custom fixed-size array `SOMStack` which,
currently, is simply an array of `Val`s. This is mostly intended to make future
work easier but, to my surprise, this also gives a 3% or so speed increase on
our simple while benchmark.
> Use a custom implementation for the SOM stack.

- src/lib/vm/core.rs
- src/lib/vm/somstack.rs
This is how I should have done things in the first place, but I'd forgotten one
of my guiding principles, which is that `VM` should (roughly) model what a
multi-threaded interpreter should look like. In that model, some sort of lock
would be need to held before `SOMStack` can be accessed, but after that
`SOMStack` should be fairly normal.
This commit thus makes VM store `SOMStack` in an `UnsafeCell`, which means we
can then remove the inner `UnsafeCell` from `SOMStack` itself.
> Move the UnsafeCell from SOMStack to VM.

- lang_tests/symbol.som
- lib/SOM/String.som
- lib/SOM/Symbol.som
- src/lib/compiler/ast.rs
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/instrs.rs
- src/lib/compiler/som.y
- src/lib/vm/core.rs
- src/lib/vm/objects/double.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/objects/string_.rs
- src/lib/vm/val.rs
Add support for the som class - `Symbol`, a subclass of `String`. In the future, this should be used to implement classes as globals so we can support class primitives.
> Add Symbol class.

- lang_tests/instance_vars2.som
- lang_tests/system_global.som
- lang_tests/system_global_invalid_symbol_err.som
- lib/SOM/System.som
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/instrs.rs
- src/lib/vm/core.rs
Add a hashmap which maps symbols to their corresponding object and retrieve an object from this hashmap when its symbol is referenced during runtime.
> Add support for globals.

- .buildbot.sh
Sometimes rust nightly and/or rustfmt are so broken that the latter won't install under any method we try. Rather than borking completely, it's better to allow the PR to be merged even without the fmt check. This is less than ideal, but I can't see a better way of doing things.
> Build even when rustfmt can't be installed.

- lang_tests/instance_var_in_block.som
- src/lib/compiler/ast_to_instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/block.rs
The `value` primitive is rather special, and before this commit we didn't implement it quite correctly. The new test instance_var_in_block.som caused this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
TypeError { expected: Inst, got: Block }', src/lib/vm/core.rs:353:39
```
The problem is that when executing a block via `value` we always set `rcv` to `Block`. This commit calls exec_primitive with an extra argument that allows it to set `rcv` to the "outer" `rcv`, fixing the problem.
> block values need to execute with their self set to the outer object

- src/lib/compiler/ast.rs
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/som.y
The main purpose of this PR is to use `lrpar`'s `Span` type, which makes the grammar slightly uglier but the compiler slightly simpler -- since there's more complexity in the latter this seems like a reasonable trade.
> Move to using spans

- src/lib/mod.rs
- src/lib/vm/core.rs
- src/lib/vm/somstack.rs
This PR is in two stages: first of all it gives `SOMStack` (the SOM stack of values) an immutable API (https://github.com/softdevteam/yksom/commit/d8cb3ce47c2495e590833efced89228f7bf55000) and then uses that to reduce the `unsafe` code in the main interpreter (https://github.com/softdevteam/yksom/commit/af582fe8138fc074c043e897ff8ff5fb944ac23e). This should make it harder to reintroduce the incorrect code we addressed in #102.
[Note that `SOMStack` is not thread-safe, but that's OK a) because the use of `Cell` means that it is not `Sync` b) SOM is single-threaded.]
> Reduce the quantity of explicitly unsafe code

- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/mod.rs
- src/lib/mod.rs
- src/lib/vm/core.rs
- src/lib/vm/error.rs
- src/lib/vm/objects/block.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/double.rs
- src/lib/vm/objects/instance.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/objects/method.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/objects/string_.rs
- src/lib/vm/somstack.rs
- src/lib/vm/val.rs
- src/main.rs
This is a fairly long, but surprisingly mostly-not-too-difficult, PR that removes `UnsafeCell`s from nearly all parts of yksom. https://github.com/softdevteam/yksom/commit/4e13c53bcf5db87d2c24dc160344788f8ecb0aab is the biggie: it makes the core `VM` struct require `&mut self` which ripples throughout the entire system (e.g. requiring a fairly large number of new intermediate variables to keep the borrow checker happy). That commit also contains the explanation which, IMHO, justifies the rest of the PR. Overall, I think this is *probably* a good idea, because it's very clear that it's hard to use large numbers of `UnsafeCell`s correctly, but there is always the possibility that this makes the VM unergonomic in the long term (I suspect that …
> Remove as many UnsafeCells as possible

- lang_tests/class_methods_fields.som
- lang_tests/metaclasses.som
- lib/SOM/Metaclass.som
- src/lib/compiler/ast.rs
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/mod.rs
- src/lib/compiler/som.y
- src/lib/vm/core.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/instance.rs
- src/lib/vm/objects/mod.rs
This PR adds support for class methods and fields, which also requires metaclasses too. I needed a bit of help from @smarr to understand this, because in essence if you define a class:
```
C = (
|x|
m1 = ( 'm1' println. )
------
|y|
m2 = ( 'm2' println. )
)
```
you're actually defining two classes. The class C is:
```
C = (
|x|
m1 = ( 'm1' println. )
)
```
and its metaclass:
```
Cclass = (
|y|
m2 = ( 'm2' println. )
)
```
The [`class_methods_fields.som`](https://github.com/ltratt/yksom/blob/f47e711582b4d6e9d43c1337904df82696445fcd/lang_tests/class_methods_fields.som) lang_test shows this in action. However, the first major step towards this is metaclasses (https://github.com/softdevteam/yksom/commit/31555a97c348860551892a83af057a4072bcd178), which is much trickier, as we have to deal with …
> Class methods and fields

- src/lib/compiler/ast_to_instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/error.rs
- src/lib/vm/objects/block.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/double.rs
- src/lib/vm/objects/instance.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/objects/method.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/objects/string_.rs
- src/lib/vm/somstack.rs
- src/lib/vm/val.rs
This PR removes many unnecessary `clone` calls now that `Gc` is `Copy` (which allows us to make `Val` `Copy` too). This is a mix of automatic and manual work.
> Remove clones

- src/lib/vm/core.rs
[This needs https://github.com/softdevteam/rboehm/pull/9 to be merged first.]
We originally used Rc here because in abgc Gc<String> was not supported; rboehm
does support this, so we can drop the use of Rc.
> Change our sole use of Rc to Gc.

- lib/SOM/Symbol.som
- src/lib/compiler/ast_to_instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/double.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/objects/string_.rs
- src/lib/vm/val.rs
SOM has `String` and `Symbol` types where the latter is a subclass of the former. This is a bit awkward to model in Rust. Previously `String_`s had an `is_str` boolean (true for `String`, false for `Symbol`), which meant that we ended up branching on it quite often.
This PR changes that so the creator of a string has to specify if they're creating a SOM `String` (`String_::new_str`) or a `Symbol` (`String_::new_sym`), allowing us to embed the appropriate class in the `String_` struct itself. This doesn't increase the size of the struct (since the `is_str` bool was rounded up to a machine word anyway), and it removes all the subsequent branches.
This does however make bootstrapping the VM a bit messier. The last two commits in this PR try to make that part of the code a little less awkward …
> Remove the is_str attribute from String_

- lang_tests/system_global_lookup_string.som
- lang_tests/system_global_put_string.som
- src/lib/vm/core.rs
- src/lib/vm/error.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/val.rs
This PR has a simple goal in mind (`global:s` should raise an error if `s` is anything other than a SOM `Symbol`), but has to go through some hoops to get there. It might be easiest to start with the last commit (https://github.com/softdevteam/yksom/commit/6f14292fc172cd739924a222ef5d11a02d45e810) to see what the goal is.
The challenge is then set out in the commit message https://github.com/softdevteam/yksom/commit/fc3f3f9eebf0fa4c4ba449d98cce2f08c8baf2a0: in essence, at least internally to the VM, there are two different kinds of type errors, and previously we only supported one. So this PR adds a second kind (after renaming things a bit in https://github.com/softdevteam/yksom/commit/c569349966d2e5c709dca5f720d0cfb74b1f9d7e) so that, ultimately, we can raise the error message you see in …
> Raise errors when passing a string instead of a symbol

- lang_tests/binary_super.som
- lang_tests/super_var.som
- lib/SOM/Symbol.som
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/instrs.rs
- src/lib/mod.rs
- src/lib/vm/core.rs
In SOM, "super" is mostly an alias for "self" *except* when you get a message send such as "super x" which means "call the method 'x' in my superclass (or, if not found, recursively in its superclasses)". This allows us to make another part of Symbol.som identical to the SOM standard library.
> super sends

- lib/SOM/Object.som
- lib/SOM/System.som
This was only ever temporarily placed in Object; the proper home for it is System.
> Move exit primitive to the System class.

- lang_tests/double_asinteger.som
- lib/SOM/Double.som
- src/lib/vm/core.rs
- src/lib/vm/objects/double.rs
Our implementation is rather inefficient, since we convert immediately to a BigInt, but it is simple and hopefully correct.
> Implement Double.asInteger.

- lang_tests/empty_block.som
- src/lib/compiler/ast_to_instrs.rs
- src/lib/vm/core.rs
Whilst here, it is silly for `add_global` to take a `String` when both callers have to call `to_owned` for the `&str` they really have.
Note this is different behaviour from (at least) Java SOM (see https://github.com/SOM-st/SOM/issues/36).
> Empty blocks evaluate to nil.

- lang_tests/mutate_methods.som
- lang_tests/mutate_superclass_method/test.som
- lang_tests/mutate_superclass_method/test_super.som
- src/lib/compiler/ast_to_instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/array.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/mod.rs
- src/main.rs
This fixes the problem identified in https://github.com/SOM-st/SOM/issues/35 and which, AFAIK, affects all SOM implementations: mutating a method in a class causes incorrect behaviour if an inline cache exists for that call (e.g. yksom (before this PR) and Java SOM could "ignore" the change if a cache had been created; and C SOM apparently crashes!). This PR fixes the problem for yksom.
It does so in a brute force way: when a method in any class is changed, every inline cache in the VM is reset. This makes correctness easy to reason about, though clearly it is less efficient than more nuanced approaches.
The way we do this is sort-of interesting from a Rust perspective. There are two obvious ways to model this:
* Have every SOM `Array` have a `bool` that says "if I'm mutated, flush all …
> Invalidate inline caches on method mutation

- lang_tests/escaped1.som
- lang_tests/escaped2.som
- src/lib/vm/core.rs
- src/lib/vm/objects/block.rs
This PR calls `escapedBlock:` when a block escapes (i.e. when it tries to return a value even though the closure it was called within has already been returned from).
> Call escapedBlock:

- lang_tests/empty_method.som
- src/lib/compiler/ast_to_instrs.rs
Before this commit, the 'empty_method' test failed because we tried to "pop" an empty SOM stack.
> Methods with no expressions have nothing to pop before returning.

- lang_tests/binary_super.som
- src/lib/vm/error.rs
- src/lib/vm/objects/class.rs
This makes it much easier to work out what the root cause of the dynamic typing error is.
> Print out the class name when a method is not found.

- lang_tests/fast_integer_comparisons.som
- src/lib/vm/objects/integers.rs
I had neglected to consider the difference between positive and negative big ints in these comparisons, leading to the original `debug_assert`s firing (which is good, because the code after the `debug_assert`s was wrong!).
> Fix fast-path integer comparisons between big ints and normal ints.

- lang_tests/array_literals.som
- src/lib/compiler/som.y
The grammar previously required, incorrectly, at least one item in array literals.
> Array literals don't have to have any items in them.

- lang_tests/instance_fields.som
- lang_tests/mutate_fields.som
- src/lib/vm/core.rs
- src/lib/vm/objects/class.rs
This returns a class's fields. However, SOM's semantics on this are currently unclear (see https://github.com/SOM-st/SOM/issues/40). Although we allow users to mutate the 'methods' array, this is less sensible with fields in my opinion, since it would turn SOM from a statically into a dynamically scoped language. Thus, each time you call 'fields' you get a fresh array back such that any mutations made are ignored (see the `mutate_fields` test).
> Add the 'fields' primitive.

- lang_tests/hashcode.som
- src/lib/vm/core.rs
- src/lib/vm/objects/array.rs
- src/lib/vm/objects/block.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/double.rs
- src/lib/vm/objects/instance.rs
- src/lib/vm/objects/method.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/objects/string_.rs
- src/lib/vm/val.rs
In an ideal world, we'd probably define the 'hashcode' function in 'Obj' to be something like:
```
fn hashcode(&self) -> u64 {
hash(self as *const _ as usize)
}
```
However we can't coerce the `Self` type in traits without causing a number of problems that we don't want to go into. So every type has to implement the `hashcode` function.
> Implement the 'hashcode' primitive.

- lang_tests/fullgc.som
- src/lib/vm/core.rs
We do not actually do a GC, since a) we have no way of forcing one b) asking a VM to GC should be a hint rather than a request so not doing anything is a valid thing to do anyway.
> Implement the 'fullGC' primitive.

- lang_tests/remainder.som
- lang_tests/remainder_zero.som
- src/lib/vm/core.rs
- src/lib/vm/error.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/val.rs
This calculates remainders. Fully implementing this for all the possible types is surprisingly tricky because BigInt doesn't provide `checked_rem`. Since Java SOM also can't deal with any of the tricky cases (a big int / non-big int errors with "TODO"), I think the very basic support here is just about acceptable.
> Partiallly implement the 'rem:' operator.

- lang_tests/to32bits.som
- src/lib/vm/core.rs
Java SOM crashes on big integers, so I have defined what I believe to be appropriate semantics for them which appears to be not to perform sign extension in the conversion. For example:
```
((1 << 60) - 1) as32BitUnsignedValue
```
in Java SOM returns 4294967295, which is bigger than a signed 32 bit can represent. This commit preserves that behaviour.
> Implement the 'as32Bit[Un]signedValue' primitives.

- lang_tests/instance_fields_overlap/test.som
- lang_tests/instance_fields_overlap/test_super.som
- lang_tests/instance_fields_overlap2.som
- src/lib/compiler/ast_to_instrs.rs
There are two cases to be dealt with:
1. A field name has already been defined in a superclass (https://github.com/softdevteam/yksom/commit/5e00d91257a8865f90f0836e65bbcddb237078a5).
2. A class defines the same field more than once (https://github.com/softdevteam/yksom/pull/147/commits/93706090edfdcd26f2a0e82032500bd19a0f3686).
The first of those was pointed out by @hirevo in https://github.com/SOM-st/SOM/issues/42; the second is a relatively simple variation on the same theme.
> Detect overlapping field names

- lang_tests/shift_right.som
- lang_tests/shift_right_too_big.som
- lang_tests/shift_right_type_err.som
- src/lib/vm/core.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/val.rs
Java SOM seems to define "shift right" as "treat the int as unsigned, shift right, then treat as signed". This is fairly easy for us in the case of word-sized integers, but awkward to implement for negative big ints -- I've left that for the future (if anyone should ever encounter such a case, which might be quite some time away!).
> Implement the 'Shr' primitive.

- lang_tests/perform_in_superclass.som
- lang_tests/perform_in_superclass_with_args.som
- lang_tests/perform_witharguments.som
- lang_tests/perform_witharguments_wrong.som
- src/lib/compiler/ast_to_instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/error.rs
- src/lib/vm/objects/array.rs
- src/lib/vm/objects/method.rs
This PR implements the various `perform:withArguments` primitives.
Some of the complexity in https://github.com/softdevteam/yksom/pull/149/commits/ef599ea6e4f06de015c8036fdb82334c86b23119 is to make sure that yksom doesn't suffer from the same problems as JavaSOM (see https://github.com/SOM-st/SOM/issues/43#issuecomment-643378401). https://github.com/softdevteam/yksom/pull/149/commits/bf02eaa4da0ba4e1f0a9962a6a51ae79f2ef431b is then a simple general optimisation opened up by the first commit. I then factored out the common `perform` code in https://github.com/softdevteam/yksom/pull/149/commits/d58f3e886f761912338ae7fad4244b8c8345e5c2 which made implementing the other primitives relatively simple.
> Implement the 'perform:WithArguments' and friends primitives.

- src/lib/vm/val.rs
We ensure that is always greater than/less than an isize.
> An ArbInt can never be zero.

- lang_tests/inst_var_at.som
- lang_tests/inst_var_at_bad_idx.som
- lang_tests/inst_var_at_put.som
- lang_tests/inst_var_at_put_bad_idx.som
- lang_tests/inst_var_at_put_superclass/test.som
- lang_tests/inst_var_at_put_superclass/test_super.som
- src/lib/vm/core.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/instance.rs
- src/lib/vm/objects/mod.rs
These are two relatively simple primitives, although while doing this, I realised that some existing functions should be explicitly marked as `unsafe` (https://github.com/softdevteam/yksom/commit/54422e80da444b5e22e9b2e5a6a82756d3803ae1).
> Implement instVarAt:[put:]

- src/lib/compiler/ast_to_instrs.rs
This fixed through the net in https://github.com/softdevteam/yksom/pull/154 because `rustfmt` is currently broken in nightly, it seems.
> Fix formatting.

- lang_tests/is_digits.som
- lang_tests/is_letters.som
- lang_tests/is_whitespace.som
- src/lib/vm/core.rs
This PR implements the `isDigits`, `isLetters`, and `isWhitespace` primitives. They're all very related. Note that I have assumed that `isDigits` only matches *ASCII* digit characters, but that the other two primitives match *Unicode* letters/whitespace.
> Implement three string primitives

- build.rs
This is a hangover from the move from our own (hacked) version of the SOM library to a submodule of the genuine SOM repository.
> We needn't force a rebuild when something in the SOM directory changes.

- .buildbot.sh
Since https://github.com/SOM-st/SOM/pull/49 has been merged, we can now easily run the test suite, so I think it makes sense to do that during CI.
> Run the SOM testsuite on buildbot.

- src/lib/mod.rs
Recent rustc nightlies warn against using this feature so, since we don't need it, we might as well remove it.
> We don't use specialisation.

- Cargo.toml
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/mod.rs
- src/lib/vm/core.rs
- src/lib/vm/error.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/double.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/objects/string_.rs
- src/lib/vm/val.rs
- src/main.rs
The [SmartString](https://crates.io/crates/smartstring) library avoids allocating memory for strings if they're small enough to fit inside the existing String struct. This is quite appealing for an interpreter where in general there are quite a lot of small strings that are
critical for performance (e.g. function names; though, admittedly, Smalltalk has many unusually long function names).
This commit is a fairly simple port (note that we generally import `SmartString` as `String` i.e. `String` no longer means `std::string::String` as per normal). Here's how long the test suite takes on my desktop before this commit:
```
$ multitime -n 30 -s0 -q target/release/yksom --cp SOM/Smalltalk/ SOM/TestSuite/TestHarness.som
===> multitime results
1: -q target/release/yksom --cp SOM/Smalltalk/ …
```
> Use SmartString.

- src/lib/compiler/ast_to_instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/instance.rs
Because of SOM's meta-class hierarchy, it's quite easy to get a bit lost as to where you are in it. I compounded that by not understanding it at first and hacking it in a bit later. That meant that we had a variable "num_inst_vars" in classes which described how many instance variables *instances* of the class would possess, but not how many the class itself has. Since I just managed to thoroughly confuse myself over this, this commit moves a few things around so that we no longer have that attribute, which hopefully makes things a little clearer for the next person who stumbles into this part of the code.
> Clarify the layers of instance variables.

- .buildbot.sh
- src/lib/mod.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/array.rs
- src/lib/vm/objects/block.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/double.rs
- src/lib/vm/objects/instance.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/objects/method.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/objects/string_.rs
- src/lib/vm/val.rs
VM objects are all allocated on the heap. The Val::recover function turns an object back into a `Val`, but is deeply unsafe: if you didn't allocate the object via `Val::from_obj` all sorts of bad, weird things will happen. Previously we entirely relied on the programmer doing The Right Thing in order that the bad case didn't occur.
This commit makes it *much* clearer that objects are `Gc`d things by making their `self` types `self: Gc<Self>`. For example this means that String::concatenate function previously looked like this:
```rust
pub fn concatenate(&self, ...) -> Result<Val, Box<VMError>> {
...
Val::recover(self)
...
}
```
But you could call that with a non-GCd `&self` and then things would explode. This function now looks like:
```rust
pub fn concatenate(self: Gc<Self>, ...) -> …
```
> Use arbitrary self types so that we can use `self: Gc<Self>`.

- src/lib/vm/val.rs
The "to t[hin]obj" functions in `Val` are fairly heavily used: this PR slightly tidies them up. No functional change.
> Simplify tobj functions

- src/lib/vm/objects/string_.rs
Calculating the number of Unicode characters in a string is an O(n) operation. Previously everytime `String_::length` was called we iterated over the underlying string to discover how many Unicode characters it contains.
This commit adds a field to SOM strings that stores its number of Unicode characters. Since not all strings will be queried for this property, we lazily cache this property the first time that `length` is called on a `String_`. We use `usize::max` as our marker as that means the marker is "safe" in all cases.
On the JSON benchmark, with GC off, this speeds things up by about 80%.
Needs https://github.com/softdevteam/rboehm/pull/19 to be merged first.
> Lazily store the number of Unicode characters a string contains.

- src/lib/vm/core.rs
This function is one of the most frequently called in yksom, so the fact that it serves two different masters (methods and blocks) is less than ideal (at the very least it introduces a branch). This commit splits the function into two, one for methods and one for blocks.
To some extent this is a bit pointless in that the major overhead of `Frame::new` is the malloc of a `Vec`, but one day that cost will be much less, so this change seems like a useful one, if perhaps a bit early!
This can be reviewed but won't be mergeable until https://github.com/softdevteam/rboehm/pull/19 is merged.
> Split `Frame::new` into two.

- src/lib/vm/val.rs
Needs https://github.com/softdevteam/rboehm/pull/19 to be merged first.
At the moment a `Val` can only be `INT` or `GCBOX`, so in cases where we've checked to see if `self` is an `INT`, the only remaining case is `GCBOX`. The locations changed in this commit implicitly checked that `self` was a `GCBOX`
twice: by using unsafe `gcbox_to_tobj` function, we can remove the second (pointless) check. This is a just about measurable improvement on the JSON benchmark at about 1%.
> Remove calls to tobj() when we know we must have a GCBOX.

- bors.toml
- src/lib/compiler/ast_to_instrs.rs
- src/lib/mod.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/array.rs
- src/lib/vm/objects/block.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/double.rs
- src/lib/vm/objects/instance.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/objects/method.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/objects/string_.rs
- src/lib/vm/val.rs
**Draft PR: we need to check that we're confident this really does what we think it should do, as it uses a new-ish Rust feature.**
Previously we created objects on the stack and then moved them into the heap. Mostly this is cheap (and most of the moves were probably optimised away), but it is clearly inefficient for large objects, and it also limits us to objects that are a fixed size.
This commit changes the object creation API substantially. Objects now request a chunk of heap via `Val::heap_obj`, to which they are handed a raw pointer, to which they must write a fully initialised object. We use a function for this, so that the bounds of uninitialisation are clear. For example previously we wrote:
```rust
pub fn from_vec(vm: &mut VM, store: Vec<Val>) -> Val {
Val::from_obj(
vm, …
```
> Create variable sized objects

- src/lib/vm/core.rs
- src/lib/vm/objects/array.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/somstack.rs
- src/main.rs
This PR makes `NormalArray` (fixed sized arrays in SOM) perform a single allocation (similar to how `Inst` is stored after #172), and also changes a couple of cases to not allocate intermediate `Vec`s.
> Normal array fewer allocations

- src/lib/compiler/ast_to_instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/block.rs
This PR slightly reduces the size of `Block`s. Since these are instantiated regularly at run-time on the heap, any saving helps!
> Smaller blocks

- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/instrs.rs
- src/lib/vm/core.rs
"Up variables" is the Lua terminology for "variables in an outer closure". By separating out variables local to the current closure from those in an outer closure, we do get a small speed increase (3-4% on the JSON benchmark), but more importantly we start to move the VM in a direction where we can put variables on the stack.
> Separate out local variable lookup/set from up-variables.

- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/error.rs
- src/lib/vm/function.rs
- src/lib/vm/mod.rs
- src/lib/vm/objects/block.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/method.rs
- src/lib/vm/objects/mod.rs
This PR aims to sort out the internal representation of SOM functions. The basic problem is that we previously had quite separate representations of SOM methods and blocks, and that hinders o. The major work is done in https://github.com/softdevteam/yksom/commit/9cbe414650907d79366d4f30db6c7486d8148f0e (https://github.com/softdevteam/yksom/commit/cb5b342d35032008ac332d8c7c0c967a5075459d is a simple stand-alone improvement).
> Reorganise functions

- lang_tests/block11.som
- lang_tests/block12.som
- lang_tests/escaped3.som
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/instrs.rs
- src/lib/mod.rs
- src/lib/vm/core.rs
- src/lib/vm/error.rs
- src/lib/vm/function.rs
- src/lib/vm/objects/block.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/somstack.rs
Previously each function call allocated memory for variables on the heap. This commit moves things so that most variables live and die on the SOM stack. This then enables doing many more operations on the stack, including passing function arguments in on the stack rather than through intermediate `Vec`s (see the comment in `somtack.rs`). This is a substantial speed-up (a little under 2x).
The scheme we use is, more-or-less, that of Lua's. The most approachable explanation I know of is:
http://www.craftinginterpreters.com/closures.html
though it's not something I'd expect anyone to understand in 5 minutes. The basic idea is that methods (and blocks which don't reference variables in outer methods / closures) don't require any heap allocation of variables. Blocks which reference variables …
> Store SOM variables on the SOM stack.

- src/main.rs
This changes yksom from this:
```
yksom --cp X -cp Y Z.som
```
to this:
```
yksom --cp X:Y Z.som
```
which is more in line with other SOMs.
> SOM class paths are conventionally separated by ':'.

- Cargo.toml
- src/lib/mod.rs
- src/lib/vm/objects/block.rs
- src/lib/vm/objects/string_.rs
- src/main.rs
This PR adds support for yksom to be used with rustc_boehm. If rustc_boehm is used to build yksom, the `rustc_boehm` feature flag can be passed to enable additional optimizations. E.g.:
`cargo build --release --features "rustc_boehm"`
I've identified two types in yksom which will benefit from the `NoFinalize` marker trait in `rustc_boehm`: `Block`; and `String_`. With that in place, we perform a lot better than ToT in the rebench suite: 
```
----------------------------------------------------------------------------------------------------
Benchmark     Executor                  Suite   Extra                 #Samples   Mean (ms)
----------------------------------------------------------------------------------------------------
Bounce        baseline      micro       2      1 …
```
> Add support for rustc_boehm

- Cargo.toml
This needs merging before https://github.com/softdevteam/yksom/pull/192 can land.
> Set Boehm as GC backend explicilty

- src/lib/vm/core.rs
- src/lib/vm/objects/double.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/val.rs
The main objective of this PR is to  make `Val::as_isize` return `Result<...>`.
This not only brings it in line with as_usize, but means that if the user makes a dynamic type error that passes a non-int to code that calls as_isize, they'll get a backtrace rather than an internal compiler error!
@jacob-hughes It might be interesting for you (and me!) to do a Krun run before and after this PR? The first commit (probably) reduces overhead while the second commit *might* introduce some overhead. [The second commit is arguably a correctness fit, so I wouldn't reject it for performance reasons; but it might still be interesting to know what the overall effect is!]
> Homogenise as_isize's return types

- src/lib/vm/objects/double.rs
- src/lib/vm/objects/integers.rs
Other SOMs that I've tried error (whether deliberately or not) when a big integer is too big to be represented as a floating point number. The `BigInt::to_f64()` function used to return `None` in such cases but now they always return `Some::(f64::INFINITY)` (see https://github.com/rust-num/num-bigint/pull/163). This PR handles that explicitly.
On the plus side, we can simplify our code a little bit; on the downside we'll also probably be a tiny bit slower in the common case.
> We need to check BigInt::to_f64() for infinity explicitly.

- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/instrs.rs
- src/lib/vm/core.rs
This is needed to support a recent test added to the SOM test suite.
I could do a more sophisticated job here (such as caching the ArbInt objects), but this is good enough to pass the test suite, which is the first step.
> Minimally add support for arbitrary sized integer constants.

- bors.toml
Especially if the build server is performing other tasks at the same time, 10 minutes is starting to cut things a bit fine, and may explain the occasional bors timeouts we've seen recently.
> yksom takes a while to build so allow up to 30 minutes.

- .buildbot.sh
- Cargo.toml
- src/lib/compiler/ast_to_instrs.rs
- src/lib/mod.rs
- src/lib/vm/core.rs
- src/lib/vm/error.rs
- src/lib/vm/function.rs
- src/lib/vm/objects/array.rs
- src/lib/vm/objects/block.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/double.rs
- src/lib/vm/objects/instance.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/objects/method.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/objects/string_.rs
- src/lib/vm/somstack.rs
- src/lib/vm/val.rs
- src/main.rs
This PR tries to move yksom from `rboehm` to `libgc`. However it fails to compile with:
```   Compiling libgc v0.1.0 (/home/ltratt/libgc)
error[E0603]: trait `GlobalAlloc` is private
--> src/lib.rs:23:25
|
23 | pub use libgc_internal::GlobalAlloc;
|                         ^^^^^^^^^^^ private trait
|
note: the trait `GlobalAlloc` is defined here
--> /home/ltratt/.cargo/git/checkouts/libgc_internal-b80cf56d30ac30df/7e79d84/src/lib.rs:14:36
|
14 |     alloc::{AllocError, Allocator, GlobalAlloc, Layout},
|                                    ^^^^^^^^^^^
error[E0603]: trait `GlobalAlloc` is private
--> src/lib.rs:23:25
|
23 | pub use libgc_internal::GlobalAlloc;
|                         ^^^^^^^^^^^ private trait
|
note: the trait `GlobalAlloc` is defined here
--> …
```
> Move from rboehm to libgc.

- .buildbot.sh
- Cargo.toml
- src/lib/mod.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/array.rs
- src/lib/vm/objects/block.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/somstack.rs
- src/main.rs
This updates various places in yksom to work after the following breaking changes to libgc:
- `Gc<T>` can no longer be mutably dereferenced, so the places in yksom which relied on this have been updated to use interior mutability instead.
- `Gc<T>` now requires `T: Send`, so the `Obj` and `Array` traits needed updating with this constraint also.
Please can you pay special attention to the changes I've made in `UpVars`. The first couple of times I'd tried this, I had broken the `block.som` and `escape{n}.som` tests. I seem to have got this working now, I'd got very confused over whether in places I needed to be taking the on-stack-reference, or the `usize` field inside `Val`.
> Fix yksom after libgc changes

- src/lib/vm/objects/block.rs
- src/lib/vm/somstack.rs
I've done a lightweight audit of some of the interior mutability in SOM `UpVar`s that we once thought caused a problem (see the commit message of cb0f27142b91fff4fbabe84e0c3fd82a4391fd4f). I believe that the problem was fixed by 687a8f053e06ced374fff8dc678d0205472e4141 which made `UpVar`'s attributes `Cell`s (although I think it might have been an unintentional, or at least, incidental part of that commit; the subsequent commit 78ee9e02338210dfd48540bac05438f45747f662 in retrospect seems like it was intended to do that; not that this matters, as they were part of the same PR).
The only minor thing I could see was some unnecessary casting (my fault originally!) which I've fixed in https://github.com/softdevteam/yksom/commit/fb171e2a5fc849b38ddb981246922689c3c1285e. However, I have …
> Audit interior mutability

- .gitignore
- Cargo.toml
- src/lib/mod.rs
- src/lib/vm/objects/array.rs
- src/lib/vm/somstack.rs
- src/lib/vm/val.rs
Some types (e.g. `Val`) have opaque pointers which are hidden from type system. This ensures that the GC can see them and still treats them as potential pointers during marking.
> Ensure yksom works safely with untraceable allocation

- src/lib/vm/core.rs
- src/lib/vm/objects/array.rs
- src/lib/vm/objects/block.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/instance.rs
- src/lib/vm/objects/method.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/val.rs
This will make the later conversion to `Rc::as_ptr` easier.
Needs https://github.com/softdevteam/rustgc/pull/72 to be merged first.
> Move from `Gc::into_raw` to `Gc::as_ptr`.

- lang_tests/int32.som
- src/lib/vm/val.rs
Previously we didn't detect some cases of overflow properly due to integer tagging.
Spotted indirectly by @smarr in #217.
> Fix integer multiplication.

- lang_tests/string_equal_nonstring.som
- lang_tests/symbol.som
- src/lib/vm/objects/string_.rs
This commit updates us to the latest SOM library and also adapts to the new semantics of `=` for `String`/`Symbol` (see https://github.com/SOM-st/SOM/pull/106).
I believe that most (all?) SOMs currently cache symbols so two instances of `#a` in different parts of the source code always point to the same underlying object, so `=` (nominally "reference equality") will return true when those two seemingly separate objects are compared. yksom does not cache symbols, so we have to override `=` to compare `Symbol`s by their contents. This commit also does that for `String`s -- I don't think the SOM spec says anything about this either way, and all the tests pass so...
CC @smarr
> Update for symmetric `=`.

- .buildbot.sh
https://github.com/SOM-st/SOM/pull/82 changed how the benchmark runner works, but we didn't notice, and confused ourselves! With luck, this addition might spot such problems in the future.
[CC @smarr -- and thanks!]
> Run a benchmark in CI to make sure that we catch changes to the runner.
