- src/lib/vm/objects.rs
- src/lib/vm/vm.rs
There is some inherent ickiness here, because given a `Val`, you always have to call `gc_obj` in order to get a `ThinObj`. From Rust's perspective, the resulting `ThinObj` is a temporary value (which can be quite confusing when you start borrowing things).
Perhaps surprisingly, this gives us an opportunity: we can't put casting on `Val` because if it's unboxed, we have to create a boxed version, which creates a temporary which we can't then borrow from. However, by putting `cast` on `ThinObj` we sidestep the problem entirely: we get a (relatively) nice way of casting (including generating a `VMError` which records what type we expected, and what we actually got) while avoiding introducing any new borrow checking problems.
> Provide a nicer way of casting to a concrete Obj type.

- Cargo.toml
- lang_tests/instance_vars1.som
- lang_tests/instance_vars2.som
- lib/SOM/Nil.som
- src/lib/compiler/ast.rs
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/cobjects.rs
- src/lib/compiler/instrs.rs
- src/lib/compiler/som.y
- src/lib/vm/objects.rs
- src/lib/vm/vm.rs
- src/main.rs
This adds support for instance variables. The main commit is https://github.com/softdevteam/yksom/commit/64769be20df3966b506c592bb451e0535839481c and the tests in there hopefully give a good idea about what's going on.
> Add support for instance vars

- lang_tests/run.rs
`cargo run` has a noticeable overhead of about 0.1s vs. running a binary directly. Normally this isn't a problem worth bothering about, but since we're starting to grow an ever larger number of language tests, this starts to add up. On my main development branch (which has 22 language tests) on a 4 core machine, this cuts the testing time down from 3s to 2s (if I force only 1 core to be used, it cuts the time down from 10s to 7s, so this patch is more advantageous the fewer cores you have). That might not sound like much, but we're only going to grow more and more language tests over time...
> Don't use cargo run in lang tests.

- src/lib/vm/objects.rs
We previously, unintentionally, undermined Rust's type system: you could have an object with lifetime 'a, move it into a `Val`, and the lifetime disappeared. This commit minimally fixes the only instance of this (in `Class`) and prevents anyone doing this again by having `Val::from_obj` force a `'static` lifetime on anything from which a `Val` is created.
> Val's cannot contain references.

- src/lib/vm/objects.rs
- src/lib/vm/vm.rs
This is a deceptively simple PR and I can't believe it didn't occur to me earlier. In essence, we add a new trait `NotUnboxable` which if implemented for a SOM object means "this struct can never be unboxed". In our case, we implement this trait for everything except `Int`s. If you want to downcast a `Val` to a given `NotUnboxable` object type you can then change:
```
let str_tobj = rcv.tobj(self)?;
let str_: &String_ = downcast(&str_tobj)?;
```
into:
```
let str_: &String_ = rcv.gcbox_downcast(vm)?;
```
Not only is this much simpler to write and read, but a) we can now statically detect when you're trying to do an illegal `gcbox_downcast` (e.g. you get a compile-time error if you try to downcast to an `Int`) b) we remove a check and branch from the performance critical `gcbox_downcas` …
> Simplify casting.

- src/lib/vm/objects.rs
- src/lib/vm/vm.rs
Two minor cleanups of code around casting: no functional change, but this makes the code a little bit easier to work with.
> Casting cleanup

- .travis.yml
My previous attempt incorrectly plonked everything in the top-level, which is unsatisfying.
> Try a different way to get the docs into the right place.

- README.md
- src/lib/compiler/mod.rs
- src/lib/mod.rs
- src/lib/vm/mod.rs
- src/lib/vm/val.rs
- src/lib/vm/vm.rs
Needs #41 to be merged first. Addresses #38.
This PR fleshes out the README a bit. Since the README now links to the internal API docs, it also makes sense to flesh those out a little bit too. A lot more *could* be done here, but this is a start, at least.
> Flesh out the README a little bit.

- lang_tests/block10.som
- lang_tests/block9.som
SOM class names should match the file name.
> Fix class names.

- .buildbot.sh
**DON'T MERGE YET:** I'm testing webhooks.
A webhook will force these to be built elsewhere when a PR is merged.
> Don't build docs on our CI server.

- lang_tests/objects_evaluate_to_themselves.som
- lib/SOM/Object.som
@ummarikar You can review this one. Check it over carefully: if you are happy with it then you can say bors r plus (with a '+' not 'plus'!).
bors delegate @ummarikar
> Objects evaluate to themselves unless overridden.

- lang_tests/ic1.som
I stupidly forgot to add this as part of https://github.com/softdevteam/yksom/pull/62, but better late than never!
> Add missing inline cache test.

- lang_tests/bool4.som
- lib/SOM/Boolean.som
Add && for Boolean objects along with a test for all possible true and false combinations.
> Add && operator for Boolean objects.

- lang_tests/bool5.som
- lib/SOM/Boolean.som
Add || operator for Boolean objects along with tests - Boolean || Block tests (including tests which ensure that the Block is not evaluated when the Boolean is true and is evaluated when the Boolean is false) and Boolean || Boolean tests.
> Add || operator for Boolean objects.

- src/lib/vm/val.rs
This function has a very strong precondition which, if violated, will cause all sorts of weird things to happen. Marking it `unsafe` makes it more likely that callers of this function will check carefully that they're using it correctly.
> Make `val_to_obj` unsafe.

- lang_tests/fib.som
As suggested by @smarr in https://github.com/softdevteam/yksom/pull/77#issuecomment-555062043. The test passes fine.
> Add Fibonacci test.

- COPYRIGHT
- LICENSE-APACHE
- LICENSE-MIT
- build.rs
- lang_tests/run.rs
- src/lib/compiler/ast.rs
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/instrs.rs
- src/lib/compiler/mod.rs
- src/lib/compiler/som.y
- src/lib/mod.rs
- src/lib/vm/core.rs
- src/lib/vm/mod.rs
- src/lib/vm/objects/block.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/double.rs
- src/lib/vm/objects/instance.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/objects/method.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/objects/string_.rs
- src/lib/vm/val.rs
- src/main.rs
Most of the copyright in this project is held by King's. Umar Marikar retains his own copyright and has explicitly given his assent to this relicensing.
> Move to our new licensing regime.

- src/lib/vm/core.rs
- src/lib/vm/objects/integers.rs
@ummarikar Assuming you're OK with this PR, I *think* you can rplus this without me delegating.
> Suggestions from Clippy.

- lang_tests/class_superclass.som
- lib/SOM/Class.som
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/class.rs
It should be possible to return the superclass of a given class in SOM.
> Add superclass primitive to `Class`.

- lang_tests/vars_in_nested_blocks.som
Test from @smarr -- thanks!
bors delegate=ummarikar
> Add a more extensive test of nested blocks.

- src/lib/vm/core.rs
There were some incorrect uses of `UnsafeCell`, in particular (though not only) code such as the following:
```
unsafe { &mut *self.stack.get() }.push(stry!(
rcv.greater_than_equals(self, unsafe { &mut *self.stack.get() }.pop())
));
```
Notice that this holds two separate mutable references (without reborrowing) to the same `UnsafeCell` and is clearly incorrect. Rewriting it to:
```
let v = stry!(rcv.greater_than_equals(self, unsafe { &mut *self.stack.get() }.pop()));
unsafe { &mut *self.stack.get() }.push(v);
```
is both correct and, happily, easier to read!
> Audit all uses of `UnsafeCell`s.

- Cargo.toml
- lang_tests/system_global_lookup_string.som
- src/lib/compiler/ast_to_instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/error.rs
- src/lib/vm/objects/block.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/double.rs
- src/lib/vm/objects/instance.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/objects/method.rs
- src/lib/vm/objects/mod.rs
- src/lib/vm/objects/string_.rs
- src/lib/vm/val.rs
- src/main.rs
All tests for this should be pass, but let me know if you find bugs or have problems building things on OpenBSD!
> Switch out abgc for rboehm

- lang_tests/load_string.som
- src/lib/compiler/ast_to_instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/string_.rs
- src/main.rs
This PR refactors class loading to be a little more like other SOMs, and also to take advantage of other recent changes in yksom to clear up other code.
> Nicer class loading

- src/lib/vm/core.rs
- src/lib/vm/objects/integers.rs
- src/lib/vm/val.rs
This PR makes two simplifications to yksom's internals that I've realised will be useful based on another PR I'm currently working on -- in both cases, the APIs were created very early in yksom's development when we weren't quite sure what the right shape of things should be. The commit messages hopefully make clear the motivation for each change.
> Integer simplifications

- src/lib/compiler/ast_to_instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/error.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/instance.rs
- src/lib/vm/objects/string_.rs
- src/lib/vm/val.rs
This reflects the change in https://github.com/softdevteam/natrob/pull/14#issuecomment-635622030.
> Adjust to the new natrob API that returns Gc from downcast.

- lang_tests/str_escape_unknown.som
- lang_tests/str_escapes.som
- src/lib/compiler/ast_to_instrs.rs
Some of these are hard to test in practise (backspace and form feed are not very portable these days). The spec can only be found in the SOM test suite.
> Process string escapes properly.

- lang_tests/ticks.som
- src/lib/vm/core.rs
As specified in https://github.com/SOM-st/SOM/issues/46.
> Make 'ticks' be a monotonic microsecond timer.

- src/main.rs
This allows you to do e.g.:
```
$ yksom --cp SOM/Smalltalk TestHarness -- --fail-in-efficacies
```
and the like.
> Pass through command-line arguments to the VM.

- src/lib/compiler/ast_to_instrs.rs
See https://github.com/SOM-st/SOM/issues/53 and https://github.com/SOM-st/SOM/pull/31.
> Only the first receiver in message sends should be a super send.

- lang_tests/keyword_super/superc.som
- lang_tests/keyword_super/test.som
- lang_tests/symbol.som
- src/lib/compiler/ast_to_instrs.rs
- src/lib/compiler/som.y
Both noticed when running SomSom, but we add to yksom's test suite for completeness.
> Two bug fixes

- .buildbot.sh
- lang_tests/errorprint.som
- lang_tests/errorprintln.som
- lang_tests/hello_world1.som
- lang_tests/load_file.som
- lang_tests/string_length.som
- src/lib/compiler/ast_to_instrs.rs
- src/lib/vm/core.rs
- src/lib/vm/objects/string_.rs
- src/main.rs
This PR is sufficient to get SomSom (a SOM interpreter written in SOM) up and running. Since this also serves as a large-scale test of yksom, I've added it to `.buildbot.sh`.
> Get SomSom running

- .buildbot_dockerfile_debian
- src/lib/vm/objects/block.rs
- src/lib/vm/objects/class.rs
This gives us a nice performance boost on types which use `Drop` for allocation only.
```
----------------------------------------------------------------------------------------------------
Benchmark     Executor   Suite   Extra   Core   Size   Var   #Samples   Mean (ms)
----------------------------------------------------------------------------------------------------
Bounce        flzr_opt   micro       2      1                     100          24
Bounce        baseline   micro       2      1                     100          77
BubbleSort    flzr_opt   micro       3      1                     100          22
BubbleSort    baseline   micro       3      1                     100          67
DeltaBlue     flzr_opt   macro      50      1                      10          15
DeltaBlue …
```
> Implement NoFinalize for optimisable types

- src/lib/compiler/ast_to_instrs.rs
- src/lib/vm/objects/class.rs
- src/lib/vm/objects/instance.rs
This one requires https://github.com/softdevteam/natrob/pull/41 to land first.
> Switch to use FinalizerOptional trait

- .buildbot.sh
- src/main.rs
Fixes https://github.com/softdevteam/yksom/issues/224.
@smarr Does this do things right? I've done a bit of guessing here...
> More standard command line
